config/routes.rb
Rails.application.routes.draw do
  get 'transaction/index'
  get 'transfer/index'
  post 'transfer/create'

  get 'withdraw/index'
  post 'withdraw/create'

  get 'topups/index'
  post 'topups/create'

  resources :accounts
  devise_for :users
  get 'home/index'
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  validates :name, :number, presence: true
  validates_uniqueness_of :number
  validates :number, length: { minimum: 6, maximum: 16 }

  def full_name
    "#{name}-#{number}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ApplicationRecord
  has_many :transactions
  accepts_nested_attributes_for :transactions, allow_destroy: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validate :check_wallet_user
  validates_numericality_of :price, greater_than_or_equal_to: 10000
  after_create :generate_history
  belongs_to :payment

  def check_wallet_user
    return if self.transaction_type == 'debit'

    current_wallet = Wallet.find(self.wallet_id)
    status_value = current_wallet.my_value - self.price.to_f < 0
    errors.add(:price, "Wallet not enough") if status_value
  end

  def generate_history
    TransactionHistory.create(
      transaction_id: self.id,
      payment_id:  self.payment_id,
      price: self.price,
      date: DateTime.now.strftime("%Y-%m-%d")
    )
  end

  def format_price
    ActionController::Base.helpers.number_to_currency(price, unit: 'Rp ', precision: 2)
  end
end

app/models/transaction_history.rb
class TransactionHistory < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   after_create :generate_wallet

  has_one :wallet

  def generate_wallet
    dwall = Wallet.new
    dwall.address =  SecureRandom.base64(16)
    dwall.user_id = self.id
    dwall.save
  end

  def full_address
    "#{email} #{wallet.address}"
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user

  def my_value
    debit = Transaction.where(transaction_type: "debit", wallet_id: id).sum("price")
    credit = Transaction.where(transaction_type: "credit", wallet_id: id).sum("price")
    total =  debit - credit
    total
  end

  def my_cash
    ActionController::Base.helpers.number_to_currency(my_value, unit: '', precision: 2)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < BaseController
  before_action :set_account, only: %i[show edit update destroy]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.where(user_id: current_user.id)
  end

  # GET /accounts/1 or /accounts/1.json
  def show; end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit; end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)
    @account.user_id = current_user.id

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def account_params
    params.require(:account).permit(:name, :number, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[phone email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    devise_parameter_sanitizer.permit(:sign_in, keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_user!
  layout 'admin_lte_2'

  def custom_error(data)
    data.errors.messages.map { |_key, message| message.last.to_s.titleize }.join(', ')
  rescue StandardError
    "Failed #{data.errors.messages}"
  end
end

app/controllers/home_controller.rb
class HomeController < BaseController
  def index; end
end

app/controllers/topups_controller.rb
class TopupsController < BaseController
  def index
  end

  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to '/topups/index', notice: 'Topup was successfully created' }
      else
        format.html { redirect_to request.referer, notice: custom_error(@payment) }
      end
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:account_number, :account_name, transactions_attributes: [:price, :transaction_type, :date, :status, :wallet_id])
  end
end

app/controllers/transaction_controller.rb
class TransactionController < BaseController
  def index
    @transactions = Transaction.where(wallet_id: current_user.wallet.id).order('id desc')
  end
end

app/controllers/transfer_controller.rb
class TransferController < BaseController
  def index
    @users = User.where.not(id: current_user.id)
  end

  def create
    @user = User.find_by_id(params[:user_id])
    return request.referer, notice: 'please select user' if @user.nil?

    params[:payment][:account_number] = @user.id
    params[:payment][:account_name] = @user.wallet.address
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to '/transfer/index', notice: 'Transfer was successfully created' }
      else
        format.html { redirect_to request.referer, notice: custom_error(@payment) }
      end
    end
  end

  def payment_params
    params.require(:payment).permit(:account_number, :account_name, transactions_attributes: [:price, :transaction_type, :date, :status, :wallet_id])
  end
end

app/controllers/withdraw_controller.rb
class WithdrawController < BaseController
  def index
    @accounts = Account.where(user_id: current_user.id)
  end

  def create
    @account = Account.find_by_id(params[:account_id])
    return redirect_to '/withdraw/index', notice: 'please select account' if @account.nil?

    params[:payment][:account_number] = @account.number
    params[:payment][:account_name] = @account.name
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to '/withdraw/index', notice: 'Withdraw was successfully created' }
      else
        format.html { redirect_to request.referer, notice: custom_error(@payment) }
      end
    end
  end

  def payment_params
    params.require(:payment).permit(:account_number, :account_name, transactions_attributes: [:price, :transaction_type, :date, :status, :wallet_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bank_list
    ['Bank Mandiri',
     'Bank Rakyat Indonesia (BRI)',
     'Bank Central Asia (BCA)',
     'Bank Negara Indonesia (BNI)',
     'Bank Tabungan Negara (BTN)',
     'Bank CIMB Niaga',
     'Bank OCBC NISP.',
     'Panin Bank']
  end
end

app/helpers/topups_helper.rb
module TopupsHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/helpers/transfer_helper.rb
module TransferHelper
end

app/helpers/withdraw_helper.rb
module WithdrawHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true, html: {:class => "form-horizontal"}) do |form| %>
  <div class="box-body">
    <% if account.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

        <ul>
          <% account.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name, class: "col-sm-2 control-label" %>
      <div class="col-md-10">
        <%= form.select(:name, options_for_select(bank_list), {}, {class: "form-control"}) %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :number, class: 'col-sm-2 control-label' %>
      <div class="col-md-10">
        <%= form.text_field :number, class: 'form-control' %>
      </div>
    </div>

    <div class="box-footer">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<div class="col-xs-12">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Editing Account</h3>

      <div class="box-tools">
        <div class="input-group input-group-sm hidden-xs" style="width: 150px;">
          <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

          <div class="input-group-btn">
            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
          </div>
        </div>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
      <p id="notice"><%= notice %></p>
      <div class="col-xs-12">
        <%= render 'form', account: @account %>
      </div>
      <div class="col-xs-12">
        <%= link_to 'Back', accounts_path, class: 'btn btn-primary' %>
        <br>
        <br>
      </div>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
</div>

app/views/accounts/index.html.erb
<div class="col-xs-12">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Accounts</h3>

      <div class="box-tools">
        <div class="input-group input-group-sm hidden-xs" style="width: 150px;">
          <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

          <div class="input-group-btn">
            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
          </div>
        </div>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
      <div class="col-xs-12">
        <table class="table table-hover">
          <tbody>
            <tr>
              <th>Name</th>
              <th>Number</th>
              <th>User</th>
              <th colspan="2"></th>
           </tr>
          <% @accounts.each do |account| %>
            <tr>
              <td><%= account.name %></td>
              <td><%= account.number %></td>
              <td><%= account.user.try(:email) %></td>
              <td><%= link_to 'Edit', edit_account_path(account) %></td>
              <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-xs-12">
        <%= link_to 'New Account', new_account_path, class: "btn btn-primary"%>
        <br>
        <br>
      </div>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
</div>

app/views/accounts/new.html.erb
<div class="col-xs-12">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">New Account</h3>

      <div class="box-tools">
        <div class="input-group input-group-sm hidden-xs" style="width: 150px;">
          <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

          <div class="input-group-btn">
            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
          </div>
        </div>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
      <p id="notice"><%= notice %></p>
      <div class="col-xs-12">
        <%= render 'form', account: @account %>
      </div>
      <div class="col-xs-12">
        <%= link_to 'Back', accounts_path, class: 'btn btn-primary' %>
        <br>
        <br>
      </div>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
</div>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @account.number %>
</p>

<p>
  <strong>User:</strong>
  <%= @account.user_id %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/home/index.html.erb
<!-- inside app/views/home/index.html.erb -->
<h1>Welcome, this is the home page</h1>

app/views/layouts/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>E</b>W</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>E-</b>Wallet</span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
        <li class="dropdown messages-menu">
          <!-- Menu toggle button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope-o"></i>
            <span class="label label-success">4</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 4 messages</li>
            <li>
              <!-- inner menu: contains the messages -->
              <ul class="menu">
                <li><!-- start message -->
                  <a href="#">
                    <div class="pull-left">
                      <!-- User Image -->
                      <img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image"/>
                    </div>
                    <!-- Message title and timestamp -->
                    <h4>
                      Support Team
                      <small><i class="fa fa-clock-o"></i> 5 mins</small>
                    </h4>
                    <!-- The message -->
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li><!-- end message -->
              </ul><!-- /.menu -->
            </li>
            <li class="footer"><a href="#">See All Messages</a></li>
          </ul>
        </li><!-- /.messages-menu -->

        <!-- Notifications Menu -->
        <li class="dropdown notifications-menu">
          <!-- Menu toggle button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">10</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 10 notifications</li>
            <li>
              <!-- Inner Menu: contains the notifications -->
              <ul class="menu">
                <li><!-- start notification -->
                  <a href="#">
                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                  </a>
                </li><!-- end notification -->
              </ul>
            </li>
            <li class="footer"><a href="#">View all</a></li>
          </ul>
        </li>
        <!-- Tasks Menu -->
        <li class="dropdown tasks-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-flag-o"></i>
            <span class="label label-danger">9</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 9 tasks</li>
            <li>
              <!-- Inner menu: contains the tasks -->
              <ul class="menu">
                <li><!-- Task item -->
                  <a href="#">
                    <!-- Task title and progress text -->
                    <h3>
                      Design some buttons
                      <small class="pull-right">20%</small>
                    </h3>
                    <!-- The progress bar -->
                    <div class="progress xs">
                      <!-- Change the css width attribute to simulate progress -->
                      <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                  </a>
                </li><!-- end task item -->
              </ul>
            </li>
            <li class="footer">
              <a href="#">View all tasks</a>
            </li>
          </ul>
        </li>
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <img src="/assets/user2-160x160.jpg" class="user-image" alt="User Image"/>
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs"><%= current_user.try(:email) %></span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image" />
              <p>
                Alexander Pierce - Web Developer
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="col-xs-4 text-center">
                <a href="#">Followers</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Sales</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Friends</a>
              </div>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: 'btn btn-default btn-flat'%>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image" />
      </div>
      <div class="pull-left info">
        <p><%= current_user.try(:email) %></p>
        <!-- Status -->
        <a href="#">RP <%= current_user.wallet.my_cash %></a>
      </div>
    </div>

    <!-- search form (Optional) -->
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search..."/>
        <span class="input-group-btn">
          <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
        </span>
      </div>
    </form>
    <!-- /.search form -->

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">HEADER</li>
        <!-- Optionally, you can add icons to the links -->
      <li class="active"><a href="/accounts"><i class='fa fa-link'></i> <span>Bank Account</span></a></li>
      <li class="active"><a href="/topups/index"><i class='fa fa-link'></i> <span>Top Up</span></a></li>
      <li class="active"><a href="/withdraw/index"><i class='fa fa-link'></i> <span>Withdraw</span></a></li>
      <li class="active"><a href="/transfer/index"><i class='fa fa-link'></i> <span>Transfer</span></a></li>
      <li class="active"><a href="/transaction/index"><i class='fa fa-link'></i> <span>Transaction</span></a></li>
      </li>
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin_lte_2_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>E-Wallet | Log in</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>E-</b>Wallet</a>
  </div><!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="form-group has-feedback">
        <%= f.text_field :email, class: 'form-control', autofocus: true %>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>

      <div class="form-group has-feedback">
        <%= f.password_field :password, class: 'form-control', autocomplete: 'off' %>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <%= link_to 'sign up','/users/sign_up', class: 'btn btn-primary btn-block btn-flat' %>
            </label>
          </div>
        </div><!-- /.col -->
        <div class="col-xs-4">
          <%= f.submit 'Log in', class: 'btn btn-primary btn-block btn-flat' %>

        </div><!-- /.col -->
      </div>

    <% end %>
  </div><!-- /.login-box-body -->
</div><!-- /.login-box -->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/admin_lte_2_signup.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>E-Wallet</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>E-</b>Wallet</a>
  </div><!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">SignUp to start your session</p>
    <%= yield %>
  </div><!-- /.login-box-body -->
</div><!-- /.login-box -->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/topups/index.html.erb
<div class="box box-primary">
<div class="box-header with-border">
  <h3 class="box-title">E-wallet address <%= current_user.wallet.address %></h3>
</div>
<!-- /.box-header -->
<!-- form start -->
<form role="form" action="/topups/create" accept-charset="UTF-8" method="post">
  <input type="hidden" value="<%= form_authenticity_token() %>" name="authenticity_token"/>

  <div class="box-body">
    <div class="form-group">
      <label for="wallet">Top Up To</label>
      <input type="text" class="form-control" id="wallet" value="Balance Rp <%= current_user.wallet.my_cash %>" disabled>
    </div>

    <div class="form-group">
      <label for="nominal">Input Nominal Topup</label>
      <input type="text" class="form-control" id="nominal" placeholder="min Rp 10.000" name="payment[transactions_attributes][0][price]">
    </div>

    <div class="form-group">
      <label for="account_number">Account Number</label>
      <input type="text" class="form-control" id="account_number" value="1111111111111111" name="payment[account_number]" readonly>
    </div>

    <div class="form-group">
      <label for="account_name">Account Name</label>
      <input type="text" class="form-control" id="account_name" value="E-wallet" name="payment[account_name]" readonly>
      <input type="hidden" value="<%= current_user.wallet.id %>" name="payment[transactions_attributes][0][wallet_id]"/>
      <input type="hidden" value="<%= Time.now.strftime('%Y-%m-%d') %>" name="payment[transactions_attributes][0][date]"/>
      <input type="hidden" value="debit" name="payment[transactions_attributes][0][transaction_type]"/>
      <input type="hidden" value="1" name="payment[transactions_attributes][0][status]"/>
    </div>
  </div>
  <!-- /.box-body -->

  <div class="box-footer">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>
</div>

app/views/transaction/index.html.erb
<div class="col-xs-12">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Transactions</h3>

      <div class="box-tools">
        <div class="input-group input-group-sm hidden-xs" style="width: 150px;">
          <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

          <div class="input-group-btn">
            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
          </div>
        </div>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
      <div class="col-xs-12">
        <table class="table table-hover">
          <tbody>
            <tr>
              <th>Type</th>
              <th>Price</th>
              <th>Date</th>
           </tr>
          <% @transactions.each do |transaction| %>
            <tr>
              <td><%= transaction.transaction_type %></td>
              <td><%= transaction.format_price %></td>
              <td><%= transaction.date %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
</div>